- name: configure liinux
  hosts: linux
  gather_facts: no
  roles:
    - linux

- name: configure linux
  hosts: linux
  vars:
    ansible_user: "{{ credentials.ansible_user }}"
    ansible_port: "{{ credentials.ansible_port }}"
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - wireguard

- name: configure edge
  hosts: firewall
  vars:
    ansible_user: "{{ credentials.ansible_user }}"
    ansible_port: "{{ credentials.ansible_port }}"
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - nftables

- name: configure edge
  hosts: edge
  vars:
    ansible_user: "{{ credentials.ansible_user }}"
    ansible_port: "{{ credentials.ansible_port }}"
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - haproxy