- name: configure linux
  hosts: linux
  vars:
    ansible_user: "{{ credentials.ansible_user }}"
    ansible_port: "{{ credentials.ansible_port }}"
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no
  roles:
    - playground
