- name: check user_name parameters
  assert:
    that:
      - user.name is defined
      - user.name is string
      - user.name | length > 0
      - user.options.groups is iterable
      - user.options.groups is not mapping
      - user.options.groups is not string
      - user.options.password_secret_salt is defined

- name: 'check name groups'
  loop: '{{ user.options.groups }}'
  assert: 
    that:
      - item is string
      - item | length > 0


- name: 'add {{ user.name }}'
  when: 'user.options.login | default(true)'
  user:
    append: yes
    name: '{{ user.name }}'
    uid: '{{ user.options.uid }}'
    groups: '{{ user.options.groups }}'
    password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=32') | password_hash('sha512', user.options.password_secret_salt) }}"
    shell: "/bin/bash"

- name: 'add {{ user.name }}'
  when: 'not user.options.login | default(true)'
  user:
    append: yes
    name: '{{ user.name }}'
    uid: '{{ user.options.uid }}'
    groups: '{{ user.options.groups }}'
    shell: "/bin/false"

