- include_tasks:
    file: "{{ role_path }}/../fasttemplate/tasks/main.yaml"
  vars:
    src: "{{ role_path }}/templates"
    dest: "/home/{{ admin_user }}/test"
    patterns:
      - "*"
    exclude: []
    dirmode: 755
    filemode: 644
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    a: a
    b: b