- name: try to ping with initial credentials
  when: 'initial_credentials is defined'
  block:
    - set_fact:
      args: "{{ initial_credentials }}"
    - name: ping
      ping:
      ignore_unreachable: yes
      register: ping_result

- name: make initial install with initial credentials
  when: "initial_credentials is defined and initial_credentials.ansible_user != 'root' and ('unreachable' not in ping_result or not ping_result.unreachable)"
  become: yes
  become_method: sudo
  become_user: root
  block:
    - set_fact:
      args: "{{ initial_credentials }}"
    - include_tasks: install.yaml

- name: make initial install with initial credentials
  when: "initial_credentials is defined and initial_credentials.ansible_user == 'root' and ('unreachable' not in ping_result or not ping_result.unreachable)"
  block:
    - set_fact:
      args: "{{ initial_credentials }}"
    - include_tasks: install.yaml
    

- name: make initial install with new credentials
  vars:
    ansible_user: "{{ credentials.ansible_user }}"
    ansible_port: "{{ credentials.ansible_port }}"
  become: yes
  become_method: sudo
  become_user: root
  when: "initial_credentials is not defined or 'unreachable' in ping_result and ping_result.unreachable"
  block:
    - include_tasks: install.yaml
    

  