- name: try to ping with initial credentials
  vars:
    ansible_user: "{{ initial_credentials.ansible_user }}"
    ansible_ssh_pass: "{{ initial_credentials.ansible_ssh_pass }}"
    ansible_port: "{{ initial_credentials.ansible_port }}"
  when: 'initial_credentials is defined'
  block:
    - name: ping
      ping:
      ignore_unreachable: yes
      register: ping_result

- name: make initial install with initial credentials
  when: "initial_credentials is defined and ('unreachable' not in ping_result or not ping_result.unreachable)"
  include_tasks: install.yaml
  vars:
    ansible_user: "{{ initial_credentials.ansible_user }}"
    ansible_ssh_pass: "{{ initial_credentials.ansible_ssh_pass }}"
    ansible_port: "{{ initial_credentials.ansible_port }}"

- name: make initial install with new credentials
  vars:
    ansible_user: "{{ credentials.ansible_user }}"
    ansible_port: "{{ credentials.ansible_port }}"
  become: yes
  become_method: sudo
  become_user: root
  when: "initial_credentials is not defined or 'unreachable' in ping_result and ping_result.unreachable"
  block:
    - include_tasks: install.yaml
    

  