dns_lookups:
  APT_IPS:
    - security.debian.org
    - help.ubuntu.com
    - archive.ubuntu.com
  ACME_SH_IPS:
    - acme.zerossl.com
    - api.zerossl.com
    - api.godaddy.com

    # for acme.sh dns-01 test
    - cloudflare-dns.com
    - dns.google
    - doh.pub
    - dns.alidns.com