- name: stop ulogd2
  systemd:
    name: ulogd2
    state: stopped
    enabled: no

- name: copy ulogd_udp_json_exporter
  copy:
    src: ulogd_udp_json_exporter_amd64
    dest: /usr/local/bin/ulogd_udp_json_exporter
    mode: 0755
    owner: 0
    group: 0
  when: ansible_architecture == "x86_64"
  notify: restart ulogd_udp_json_exporter

- name: copy ulogd_udp_json_exporter
  copy:
    src: ulogd_udp_json_exporter_arm64
    dest: /usr/local/bin/ulogd_udp_json_exporter
    mode: 0755
    owner: 0
    group: 0
  when: ansible_architecture == "aarch64"
  notify: restart ulogd_udp_json_exporter

- name: copy ulogd_udp_json_exporter systemd service
  template:
    src: ulogd_udp_json_exporter.service
    dest: /etc/systemd/system/ulogd_udp_json_exporter.service
    mode: 0644
    owner: root
    group: root
  notify: restart ulogd_udp_json_exporter