
# - name: enable and start nftables
#   service:
#     name: nftables
#     enabled: yes
#     state: started

##### GITHUB IPS #####
- name: get github meta ips
  set_fact:
    github_ips: "{{ lookup('ansible.builtin.url', 'https://api.github.com/meta', split_lines=False) | from_json }}"

- name: template nftables
  block:
    - name: find filter files
      find:
        paths: "{{ role_path }}/templates/filter/{{ appName }}"
        patterns: "*.nft"
      delegate_to: localhost
      connection: local
      become: false
      loop: "{{ nftables_apps }}"
      loop_control:
        loop_var: appName
        label: "{{ appName }}"
      register: filter_files

    - set_fact:
        filter_structure: "{{ (filter_structure | default({})) | combine({ appName: filter_files.results[appNameIndex].files | map(attribute='path') | map('basename') | list }) }}"
      loop: "{{ nftables_apps }}"
      loop_control:
        loop_var: appName
        index_var: appNameIndex
        label: "{{ appName }}"

    - name: template nftables configuration
      template:
        src: 'nftables.conf'
        dest: /home/admin/nftables.conf
        mode: 0644
      register: nftables_config
    - name: template toplevel configs
      template:
        src: "{{ item }}"
        dest: "/etc/nftables.d/{{ item }}"
        mode: 0644
      loop:
        - settings.nft
        - blacklist.nft
      register: settings_config

##### ip reload tool #####
- block:
  - name: upload reload tool
    copy:
      src: reload_domains.py
      dest: /usr/local/bin/reload_domains.py
      mode: 0755
  - name: upload reload tool config
    copy:
      content: "{{ dns_lookups | to_yaml }}"
      dest: /etc/reload_domains.yaml
      mode: 0644
  - name: setup cronjob
    cron:
      name: reload_domains
      job: /usr/local/bin/reload_domains.py
      minute: "*/5"
  - name: create /etc/nftables.d directory
    file:
      path: /etc/nftables.d
      state: directory
  - name: install python3 yaml
    package:
      name: python3-yaml
      state: present
  # - name: run reload tool diff
  #   command: /usr/local/bin/reload_domains.py --diff
  #   register: reload_domains_diff
  #   changed_when: false
  #   failed_when: reload_domains_diff.rc not in [0, 2]
  # - name: run reload tool
  #   command: /usr/local/bin/reload_domains.py
  #   when: reload_domains_diff.rc == 2



- name: reload nftables
  include_tasks: reload_nftables.yaml


  
