- name: reload nftables
  block:
    - name: check nftables configuration
      command: "nft -f /home/{{ admin_user }}/nftables.conf --check"
      changed_when: false
    
    - name: apply nftables configuration
      command: "nft -f /home/{{ admin_user }}/nftables.conf"

    - name: Reset connection (for the case that the ssh connection is blocked)
      meta: reset_connection
    
    - name: apply nftables configuration
      command: "cp /home/{{ admin_user }}/nftables.conf /etc/nftables.conf"

    - name: restart nftables
      service:
        name: nftables
        state: restarted